import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Fingerprint, Braces, Blocks, Workflow, ShieldCheck, Package, Terminal, Layers3 } from 'lucide-react';
import { ExampleTabs } from './components/example-tabs';
const paths=[
  {title:'Comece a integração',desc:'Prepare a identidade, emita uma sessão e abra a primeira conversa.',href:'quick-start',icon:Terminal,tag:'01 / PRIMEIROS PASSOS'},
  {title:'Dê contexto à IA',desc:'Estado, histórico e logs autorizados, em um contrato claro.',href:'types',icon:Layers3,tag:'02 / CONTEXTO'},
  {title:'Conecte seu MCP',desc:'Consulte seu sistema e prepare ações com confirmação humana.',href:'mcp',icon:Workflow,tag:'03 / FERRAMENTAS'},
];
const resources=[{title:'Autenticação',desc:'Sessões de 15 minutos e credenciais por tenant.',href:'authentication',icon:Fingerprint},{title:'Referência da API',desc:'Requisições, respostas e limites do contrato.',href:'api-reference',icon:Braces},{title:'Widget SDK',desc:'Instalação, callbacks e ciclo de vida.',href:'widget-sdk',icon:Blocks},{title:'Homologação',desc:'Da primeira resposta à publicação verificada.',href:'integration',icon:ShieldCheck}];
export default function DevelopersPage() {
  return <div data-testid="developers-page">
    <div className="dc-announcement"><span>CONTRATO V3</span> O guia da integração atual, do backend ao chat.<Link href="/developers/changelog">O que mudou <ArrowRight size={14}/></Link></div>
    <section className="dc-hero"><div className="dc-hero-copy"><p className="dc-eyebrow"><span/>DOCUMENTAÇÃO PARA QUEM CONSTRÓI</p><h1>Seu produto.<br/>Todo o contexto.<br/><em>Um suporte melhor.</em></h1><p>Conecte a IA ao que acontece no seu sistema. Integre sessões, contexto e ferramentas com um contrato pensado para o seu time.</p><div className="dc-hero-actions"><Link className="dc-button" href="/developers/quick-start">Começar a integrar <ArrowRight size={17}/></Link><Link className="dc-text-link" href="/developers/downloads">Baixar o kit <Package size={16}/></Link></div><div className="dc-hero-labels"><span>SDK 0.2.2</span><i/> JavaScript · REST · MCP</div></div><ExampleTabs/></section>
    <section className="dc-flow" aria-label="Fluxo de integração">{[{icon:Fingerprint,n:'01',t:'Seu aplicativo',s:'Autentica a pessoa'},{icon:Layers3,n:'02',t:'Contexto autorizado',s:'Explica o que aconteceu'},{icon:Workflow,n:'03',t:'AI Support',s:'Responde com evidências'}].map((x,i)=><div className="dc-flow-node" key={x.n}><x.icon size={22}/><span><small>{x.n}</small><strong>{x.t}</strong><p>{x.s}</p></span>{i<2&&<ArrowRight className="dc-flow-arrow" size={18}/>}</div>)}</section>
    <section className="dc-start"><div className="dc-section-heading"><div><p className="dc-eyebrow">DO PRIMEIRO PASSO À PRODUÇÃO</p><h2>Encontre seu ponto de partida.</h2></div><span>Três caminhos. Uma integração.</span></div><div className="dc-path-grid">{paths.map(x=><Link className="dc-path-card" key={x.href} href={'/developers/'+x.href}><div><x.icon size={24}/><ArrowUpRight size={20}/></div><small>{x.tag}</small><h3>{x.title}</h3><p>{x.desc}</p></Link>)}</div></section>
    <section className="dc-resources"><div><p className="dc-eyebrow">TENHA A REFERÊNCIA À MÃO</p><h2>Menos adivinhação.<br/>Mais implementação.</h2><p>Exemplos copiáveis, schemas e orientações que acompanham o contrato publicado.</p><Link className="dc-text-link" href="/developers/downloads">Explorar downloads <ArrowRight size={16}/></Link></div><div className="dc-resource-grid">{resources.map(x=><Link href={'/developers/'+x.href} key={x.href}><x.icon size={20}/><span><h3>{x.title}</h3><p>{x.desc}</p></span><ArrowUpRight size={15}/></Link>)}</div></section>
    <section className="dc-bottom-callout"><div><span className="dc-eyebrow">PRONTO PARA CONECTAR?</span><h2>Configure sua integração no painel.</h2><p>Gerencie a credencial do widget, o conector MCP e as consultas do seu projeto.</p></div><Link className="dc-button" href="/admin">Abrir painel <ArrowUpRight size={17}/></Link></section>
  </div>;
}
