import type { Article } from './model';
export const article: Article = {
  slug: "quick-start",
  title: "Comece por aqui",
  category: "PRIMEIROS PASSOS",
  summary: "Da sessão autenticada à primeira conversa com contexto.",
  keywords: "bootstrap instalação início integrar",
  sections: [
    {"id": "prepare", "title": "01 · Prepare seu projeto", "text": ["Confirme o tenant do seu projeto com o operador. No painel, abra Widget integration e instale a credencial de integração no ambiente privado do seu backend. Cadastre as origens web usadas pela integração."], "note": "O ID do tenant identifica seu projeto na plataforma. Ele não substitui a organização ou loja do usuário dentro do seu aplicativo.", "links": [{"label": "Abrir configurações da integração", "href": "/admin"}]},
    {"id": "session", "title": "02 · Solicite a sessão", "text": ["Seu backend autentica a pessoa e confere vínculo e permissões atuais antes de chamar o emissor. A credencial determina o tenant; a requisição não aceita um tenant livre."], "code": "# Somente no backend. Use variáveis do ambiente privado.\ncurl --fail-with-body \\\n  https://support-ai.pontes.uk/api/widget/sessions \\\n  -H \"Authorization: Bearer $SUPPORT_INTEGRATION_CREDENTIAL\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"userId\":\"usr_exemplo\",\"userEmail\":\"\",\"userRoles\":[\"member\"],\"plan\":\"standard\"}' ", "language": "cURL"},
    {"id": "context", "title": "03 · Prepare o contexto", "text": ["Colete userState, userHistory e userLogs para a mesma pessoa. Devolva sessão e contexto pelo endpoint autenticado do seu aplicativo, com Cache-Control: no-store. Esse endpoint de bootstrap pertence ao seu backend."], "bullets": ["Use o schema oficial e dados sintéticos no primeiro teste.", "Não envie credenciais, headers ou registros de outra pessoa.", "Uma coleta que falhou deve retornar erro; não invente uma lista vazia."], "links": [{"label": "Construir o contexto", "href": "/developers/types"}]},
    {"id": "embed", "title": "04 · Monte e confira o widget", "text": ["Carregue o SDK fixado 0.2.2, implemente renovação e destruição da instância. Confirme uma resposta real e o snapshot correspondente antes de liberar."], "code": "// Depois de autenticar e revalidar a pessoa no seu backend.\n// Estes callbacks são implementados pelo seu aplicativo.\nconst data = await fetchAuthenticatedBootstrap();\nconst widget = AISupportWidget.init({\n  apiUrl: 'https://support-ai.pontes.uk',\n  tenantKey: data.tenantKey,\n  jwt: data.jwt,\n  context: data.context,\n  locale: 'pt-BR',\n  theme: 'light',\n  position: 'bottom-right',\n  onTokenRefresh: async () =>\n    (await fetchAuthenticatedBootstrap()).jwt,\n  onOpen: async () =>\n    widget.updateContext(await fetchAuthorizedContext()),\n});\n// No logout, troca de pessoa/organização/papel e unmount:\n// widget.destroy();", "language": "JavaScript", "links": [{"label": "Instalar o SDK", "href": "/developers/widget-sdk"}, {"label": "Checklist de homologação", "href": "/developers/integration"}]},
  ],
};
